### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by zldtll1** [art049/InteractiveWoodCombustion#2]
Hi, when I compiled the code, some problems arisen:

src/physics/physics_render.cpp:1:23: fatal error: glm/glm.hpp: No such file or directory
src/physics/../cuda_common/tex_anim2d.cuh:15:21: fatal error: GL/glut.h: No such file or directory

Can anybody help me about this?

**Comment by art049** [comment]
Hello,
You need the OpenGL Mathematics (GLM) library, on ubuntu it's included in the `glm` package.
Also you need glut, on ubuntu it's distributed in packages `freeglut3 freeglut3-dev` .

I updated the Readme to include these requirements 0d8a8e081fa0ba6d138933b92354748db1a25dcb

**Comment by zldtll1** [comment]
Thanks a lot for your detailed answer.
