### ISSUE TITLE
Strange result

### ISSUE THREAD

**Issue by zldtll1** [art049/InteractiveWoodCombustion#3]
Hi,
My system is Ubuntu, when I run ./main, I got this result:
![Selection_001](https://user-images.githubusercontent.com/50659824/59812327-22a5ec00-9340-11e9-9464-fb57d6a41db3.png)
Unlike the paper's results, there are no trees or fire. Does this project achieve just a little part of what is mentioned in the paper?

**Comment by art049** [comment]
Yes, unfortunately that's not the full implementation 😩

**Comment by zldtll1** [comment]
Ok, Thank you anyway.
