### ISSUE TITLE
Windows compatible?

### ISSUE THREAD

**Issue by carlosedubarreto** [art049/InteractiveWoodCombustion#4]
Sorry to ask here. I loved what I saw on two minutes paper and wanted to try, but I have almost no experience with c++

And I saw that gc++ is needed, so I thoungh it was aimed for linux distribuitions...

And what an amazing job you did @art049 incredible!!

**Comment by Creativity-is-Lacking** [comment]
[Mingw](http://mingw-w64.org/doku.php/download) is gcc/g++ and some extra's for windows. I'm currently working on building this project for windows and I'll come back when/if I get it to work. ([Direct link to Mingw for windows](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download))
[GLUT](https://www.opengl.org/resources/libraries/glut/glut37.zip)/[glew](https://sourceforge.net/projects/glew/files/glew/2.1.0/glew-2.1.0-win32.zip/download) are a bit annoying, as the header (.h) files have to be directly copied in to the Include folder within mingw, as for CUDA, I have no experience, and will report back with it...
Fellow 2 minute papers fan :)

**Comment by carlosedubarreto** [comment]
Hello @Creativity-is-Lacking .
Thanks for the answer.
If you have a github repo please share so I can follow it.

I was just thinking of this project, and my idea was toakenit a blender addon. It would be great. Maybe in some years. (If it depends on my  knowledge, or lack of it. lol)

And thanks for the explanation.

**Comment by Creativity-is-Lacking** [comment]
I've now created a [repo](https://github.com/Creativity-is-Lacking/InteractiveWoodCombustion). I haven't made much progress as CUDA has been giving me a run for my money...

**Comment by carlosedubarreto** [comment]
great I'm following it.
If find some time in the future, I could help with that, at least try. 
Thanks

**Comment by carlosedubarreto** [comment]
Hello @Creativity-is-Lacking 
After 3 full days trying, I was able to build in windows using VS2019

Here is the fork I've done
https://github.com/carlosedubarreto/InteractiveWoodCombustion

But a sad thing.... The only thing that was working was the combustion part of the project 😥

After those 3 days compiling, I just got a smoke simulation like this one
![image](https://user-images.githubusercontent.com/4061130/128708462-5b736dd6-476b-4b0c-bc20-23888e2bb314.png)

**Comment by Creativity-is-Lacking** [comment]
Well, at least it compiled... I'll take a look and see if what I can do. :)

**Comment by carlosedubarreto** [comment]
To be honest..... the only thing that it helped me was to have courage to dive into C++.
The CUDA SDK example (that comes when you install the SDK could be a much better test 😊

If you want to test what I did. I used the CUDA 10.1 to compile.

**Comment by Creativity-is-Lacking** [comment]
Unfortunately, my cuda is still acting up. On the bright side, however, I was able to run the binaries you compiled! the first major thing that jumps out at me is the shader path. If your shader files aren't located at "D:/CPP/int_wood v3 (CUDA)/x64/Debug/src/shaders/shader.vert" than update the shader location in main.cpp line 124. Other than that it seems odd that you can see a camera box upon zooming out, but I'm long out of time for today...

**Comment by carlosedubarreto** [comment]
Oh yeah, I had coded the shader location for me.. but, it didn't make much difference (setting up the correct location for the files)..

Lol... I got that same feeling when I saw only a camera and a gray ball 😅

**Comment by Creativity-is-Lacking** [comment]
Today marks the day when I have given up on fixing my cuda install. Using smoke, magic, mirrors, and virtual machines I have finally been able to compile it! I should be able to be more helpful now 😄

**Comment by carlosedubarreto** [comment]
Yey, congrats buddy 🎉

I got confused with the message, but in the end I think it was a good final result 😅
